import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {useEffect, useState} from "react";

const Home: NextPage = () => {
  const [darkMode, setDarkMode] = useState(false);

  useEffect(() => {
    const initialTheme = window.localStorage.getItem('theme');
    if (initialTheme === 'dark') setDarkMode(true);
  }, []);


  useEffect(() => {
    if (darkMode) {
      window.localStorage.setItem('theme', 'dark');
      document.documentElement.classList.add('dark');
    } else {
      window.localStorage.setItem('theme', 'light');
      document.documentElement.classList.remove('dark');
    }
  }, [darkMode]);

  
  return (
    <div className="bg-white dark:bg-black">
      <Head>
        <title>OnChain Library</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <button onClick={()=>{setDarkMode(!darkMode)}}>Toggle Dark Mode</button>
        <ConnectButton />

        <h1 className={styles.title}>
          Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a> +{' '}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
      </main>

      <footer className={styles.footer}>
        <a href="https://layerr.xyz" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at Layerr
        </a>
      </footer>
    </div>
  );
};

export default Home;
