import { ConnectWallet} from '../components/ConnectWallet';
import type { NextPage } from 'next';
import Head from 'next/head';
import {useEffect, useState} from "react";
import FileUpload from '../components/FileUpload';
import Heading from '../components/Heading';
import ThemeSwitcher from '../components/ThemeSwitcher';

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>OnChain Library</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className="min-h-screen bg-white dark:bg-black">
        <section className='p-4 md:p-8 lg:p-24'>
        <div className='flex justify-between gap-2'>
          <ThemeSwitcher />
        <ConnectWallet />
        </div>
        <Heading/>
        <FileUpload/>
        </section>
      <footer className="bg-white dark:bg-black flex justify-center items-center">
        <a href="https://layerr.xyz" className="text-primary dark:text-primary-dark" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your friends at Layerr
        </a>
      </footer>
      </main>
    </div>
  );
};

export default Home;
